---
- name: Deploy PRKL
  hosts: localhost
  gather_facts: true
  become: true

  tasks:
    - name: Cleanup vagrants
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "./backend/.vagrant"
        - "./frontend/.vagrant"

    - name: Deploy MongoDB backend
      command: vagrant up
      args:
        chdir: ./backend/
      become_user: "{{ ansible_user_id }}"
      register: progress

    - name: Show progress
      debug: msg="{{ progress.stdout }}"
      debug: msg="{{ progress.stderr }}"

    - name: Deploy Flask API frontend
      command: vagrant up
      args:
        chdir: ./frontend/
      become_user: "{{ ansible_user_id }}"
      register: progress

    - name: Show progress
      debug: msg="{{ progress.stdout }}"
      debug: msg="{{ progress.stderr }}"

    - name: Load songs into the mongoDB
      command: 'curl -F myfile=@../../../data/songs.json http://localhost:5000/songs/load/'
      delegate_to: localhost
