---
- name: Deploy PRKL
  hosts: localhost
  become: true

  tasks:
    - name: Cleanup vagrants
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "./infra/backend/.vagrant"
        - "./infra/frontend/.vagrant"


    - name: Deploy MongoDB backend
      shell:
        cmd: vagrant up
        chdir: ./infra/backend/
      register: progress

    - name: Show progress
      debug: msg="{{ progress.stdout }}"
      debug: msg="{{ progress.stderr }}"

    - name: Load testing data
      shell:
        cmd: python ./source/init_data_load.py ./data/songs.json purge 192.168.10.10:27017

    - name: Deploy Flask API frontend
      shell:
        cmd: vagrant up
        chdir: ./infra/frontend/
      register: progress

    - name: Show progress
      debug: msg="{{ progress.stdout }}"
      debug: msg="{{ progress.stderr }}"
