---
- name: Setup the MongoDB backend server
  hosts: all
  become: true

  tasks:
  - name: import public key
    shell: "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5"


  - name: install MongoDB
    apt:
      name: mongodb
      state: present
      update_cache: yes
