Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :private_network, ip: "100.0.10.10"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "backend_setup.yml"
  end
end
