Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "frontend.prkl"
  config.vm.network :private_network, ip: "192.168.10.100"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "frontend_setup.yml"
  end
end
