---
- name: update apt
  apt:
    update_cache: yes

- name: Install linux-image-extra-*
  apt:
    name: linux-image-extra-3.13.0-106-generic
    state: latest

- name: Install linux-image-extra-*
  apt:
    name: linux-image-extra-virtual
    state: latest

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest

- name: Install ca-certificates
  apt:
    name: ca-certificates
    state: latest

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: latest

- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Ensure curl is present
  apt:
    name: curl
    state: latest
  sudo: yes
  when: add_repository_key|failed

- name: Add Docker apt key
  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  args:
    warn: no
  when: add_repository_key|failed

- name: Add docker apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
    update_cache: yes

- name: Install Docker apt package
  apt:
    pkg: docker-ce
    state: latest
    update_cache: yes

- name: Ensure Docker service is installed and restarted
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Install pip
  apt:
    name: python-pip
    state: latest

- name: Install Docker Compose
  pip:
    name: docker-compose
    version: '1.9.0'

- name: Add vagrant user to the docker group
  user:
    name: vagrant
    groups: docker
    append: yes
    state: present
