Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "docker-lab.prkl"
  config.vm.network :private_network, ip: "192.168.10.10"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "prkl_provision.yml"
  end
end
