Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "docker-lab.prkl"
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "prkl_provision.yml"
  end
end
